### ISSUE TITLE
Upgrading to prompt_toolkit 2.0

### ISSUE THREAD

**Issue by oldboldpilot** [CITGuru/PyInquirer#14]
Will it take a lot to upgrade this to work with prompt_toolkit 2.0? 
Is there any help I can render to make that happen?

**Comment by CITGuru** [comment]
I am afraid to say that won't happen anytime soon. Cos upgrading to 2.0, will require a lot of work and rewiring. prompt_toolkit 2.0 was rewritten from scratch and they totally ditch Token and many other things PyInquirer depends on. What I could suggest is we create PyInquirer2 from scratch that will work with prompt_toolkit 2.0. And that will only happen once I am able to complete all TODO we still have left. I have thought of this sometime ago and that's the only solution. So people could choose the version they want.

**Comment by CITGuru** [comment]
You welcome, I'll be glad to work with you in the nearest future :handshake:

**Comment by rigogsilva** [comment]
Let's get this going. I'd be willing to help out.

**Comment by Apreche** [comment]
Just discovered PyInquirer, and it's not working for me because iPython uses prompt-toolkit 2, and that causes a conflict.

**Comment by CITGuru** [comment]
@rigogsilva Thanks for that, I'd be glad if we could work on it. @Apreche Yeah, you can't use PyInquirer on iPython cos, PyInquirer still uses Prompt toolkit 1.0

**Comment by tmbo** [comment]
Yes, happy to help out as well - let’s get this going 🚀

**Comment by tmbo** [comment]
@CITGuru how willing are you to move quick on this? We depend on this library for one of our larger projects, but the usage of prompt_toolkit is a dealbreaker because of ipythons dependency on prompt_toolkit2.

As said, I am very happy to help out. I've been looking into it and it is actually rather straight forward. I don't understand why the development for this is waiting for a minor release (why not create a bugfix branch for 1.0.x) instead of going full steam on this. 

My team needs to move fast on this, but since you have been putting so much work into maintaining this library, I also do not want to step on your tows. We'll have a prompt toolkit 2 ready version by the end of the week, the question is if it is going to be part of this project or a fork.

**Comment by CITGuru** [comment]
I really appreciate your concerns and understanding. I know how we feel when our projects depend on a good and promising project. But what turn us off is when the project is poorly maintained, I mean, that was the whole idea of PyInquirer. So I am looking at the best way to create time for managing this project.

While we wait for PyInquirer 2, I decided to release PyInquirer 1.0.3 bugfix release earlier as expected. @tmbo Its out now

**Comment by CITGuru** [comment]
@tmbo I'll be working on it this weekend so I should be able to push up what I have by monday, if all goes as schedules

**Comment by tmbo** [comment]
I did convert the list and confirm views locally, so let me know if you need them.

**Comment by tmbo** [comment]
sure - I'll create WIP PR

**Comment by tmbo** [comment]
@CITGuru I've pushed the list & confirm prompts as part of #31

**Comment by CITGuru** [comment]
@tmbo Thanks. I found something weird, still don't know how, but it seems prompt_toolkit 1 works with the changes you made for prompt_toolkit

**Comment by CITGuru** [comment]
@tmbo Was able to convert `input`, `editor` to prompt_toolkit2. So no standard design yet, still converting others, `rawlist`,`expand`, `password` (this should be fairly easy), `checkbox`

**Comment by CITGuru** [comment]
I should be done by tomorrow, its weekend here Saturday precisely, wanna rest more and back to it as soon as wake up. See ya

**Comment by tmbo** [comment]
Let me know if you need help converting any one of these.

**Comment by tmbo** [comment]
It would be great if you share your code so we can help you and collaborate on this project. Do you mind pushing your changes to a branch?

If you can't do all the work on your own, e.g. because you are short on time, you need to make sure others can help you.

**Comment by tmbo** [comment]
Because I could not wait for this to drag on further, I created a separate library https://github.com/tmbo/questionary  based on prompt toolkit 2. I tried to avoid this, but we needed to move faster for our project https://github.com/rasahq/rasa_core which uses the library.

**Comment by Woile** [comment]
fantastic @tmbo I was also needing something like that. Thanks a lot!

**Comment by tecosaur** [comment]
is PyInquirer going to move to prompt toolkit 2 any time soon? Or should I stop holding out hope and more to questionary?

**Comment by rednafi** [comment]
Prompt toolkit 0.1.14 is completely breaking ipython notebook. ```Pyinquirer 2.0``` is nowhere to be found and the library already seems fragmented. Then there is ```questionary```. Thanks for your awesome work nonetheless.

**Comment by Woile** [comment]
For people with problems with `prompt toolkit < 2.0`, there are currently 2 solutions which kinda fit:

- [questionary](https://github.com/tmbo/questionary) which supports `prompt toolkit > 2.0`
- [bullet](https://github.com/Mckinsey666/bullet) which has no dependencies as far as I can tell.

**Comment by rednafi** [comment]
@Woile ```questionary``` seems awesome, built on ```Pyinquirer```. It can directly be adopted as ```pyinquirer 2.0```. However, the development seems slow there which is quite understandable. Maybe we can create some traction there. Thanks for the info...:)

**Comment by tmbo** [comment]
@rednafi well, development is "slow" as there isn't a lot to develop at the moment. if there are features / bugs you are running into please create an issue 😃

**Comment by rednafi** [comment]
@tmbo ```questionary``` is working like a charm. Doesn't conflict with jupyter notebook which has a ```prompt_toolkit 2.0.9``` dependency. Thanks!!

**Comment by doylejg** [comment]
Just wanted to bump this thread. Are we still waiting on `pyinquirer2.0` or is the accepted solution to just move to `questionary` ?

**Comment by LuRenJiasWorld** [comment]
I'm glad to help developing PyInquirer2 as well.
Please feel free to contact me if you are ready to work.
My email is loli@lurenjia.in.

**Comment by yanlend** [comment]
Upgrading the dependency to newer versions of prompt_toolkit would be required for us. Is it still going to happen or are you recommending the move to questionary?

**Comment by jonathanslenders** [comment]
Hi everyone, this PR should upgrade to prompt_toolkit 3: https://github.com/CITGuru/PyInquirer/pull/118
Note that it also means that Python 2 support will be dropped.

**Comment by CITGuru** [comment]
Please read this, Looking for maintainer/successor. https://github.com/CITGuru/PyInquirer/issues/159

**Comment by o-nikolas** [comment]
Hey folks, now that @jonathanslenders's PR to support prompt_toolkit 3 has been merged, can a release be cut so that we can make use of this contribution?
