### ISSUE TITLE
'KeyError' when clicking on an item in list with mouse

### ISSUE THREAD

**Issue by Tioz90** [CITGuru/PyInquirer#41]
On MacOS, when I click with the mouse on any item of a PyInquirer list I get a KeyError thrown; this happens both in Terminal and in iTerm2.
I have looked through the source code and can't find a KeyError explicitly being thrown, so it must be inside some subroutine.

**Following is an example error that happens when I click on the "Test" item:**
Source code:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/32127232/53753636-04f86800-3eb2-11e9-83f9-8fa6b4276174.png">
Before clicking:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/32127232/53753729-425cf580-3eb2-11e9-9f6d-49d18f06a3a5.png">
After clicking:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/32127232/53753668-180b3800-3eb2-11e9-9774-188e4c7f98ce.png">

**Comment by Redauser** [comment]
Same on Fedora with version 1.0.3.

**Comment by CITGuru** [comment]
I'll look into this

**Comment by Redauser** [comment]
The solution is already in the pull-request!
thank you!

**Comment by CITGuru** [comment]
@Tioz90 Can you install from the repo directly to check if your error is fixed

**Comment by Tioz90** [comment]
@CITGuru it doesn't crash anymore but I'm not sure if it's correctly populating the dictionary as clicking displays in PyInquirer but my program doesn't register it.  I'll need to look into this.
Ex: clicking on elements registers in PyInquirer but no action is taken by my program
<img width="643" alt="image" src="https://user-images.githubusercontent.com/32127232/54984836-f9c7c200-4faf-11e9-9d0e-d2512fc73e7f.png">

Clicking on a separator throws an error in my Switch so I guess something is being returned.  I'[ll get back to you.

**Comment by CITGuru** [comment]
okay, will be waiting

**Comment by Tioz90** [comment]
Hi, I tested it and it's still not fixed

**Comment by Kos** [comment]
Confirmed fixed on Ubuntu as of 918f8e14f

@Tioz90 which verision did you test on? Latest tag (1.0.3) doesn't have the fix yet, have you installed the latest version from git?

**Comment by CITGuru** [comment]
@Tioz90 Can you test from that #37

**Comment by CITGuru** [comment]
@Tioz90 Are you still having this issue? Sorry for the late reply

**Comment by Tioz90** [comment]
I don’t know, I abandoned the software I was developing months ago.

**Comment by CITGuru** [comment]
Oh, I get. This has been fixed already in the current master. I will be releasing the new version to PyPI

**Comment by SchoolGuy** [comment]
So I am developing an app with your library. Thus I will test when the new version is released. My current fix is (what we should anyway do) to use `.get("key", "default value")`.

Thus a fix will look like this: https://github.com/cobbler/libcobblersignatures/commit/0a20f4abb291be2104576d7bb578473e6ebc4c54

**Comment by ilmoi** [comment]
@CITGuru I'm on version 1.0.3, which seems latest, and still getting the error on click. What am I missing?

**Comment by 1mS3r** [comment]
@CITGuru Same here, v1.0.3 and the error is present.

**Comment by HenryHoggard** [comment]
Still affects 1.0.3.
